server:
  port: 8080
spring:
  application:
    name: "savings-accounts"
  profiles:
    active: "production"
  datasource:
    url: jdbc:mysql://localhost:3306/savingsAccountDB
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "savings accounts"
    description: "Bank of Nav Savings Accounts Application"
    version: "1.6.9"
